# Generated by Django 4.2.7 on 2025-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.JSONField(default=list, help_text='List of addresses with type, street, city, state, zip, country'),
        ),
    ]
