# Generated by Django 4.2.7 on 2025-09-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_address_client_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='source_system',
        ),
        migrations.AddField(
            model_name='clientprogramenrollment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprogramenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='intake',
            name='intake_database',
            field=models.CharField(db_index=True, default='CCD', max_length=100),
        ),
        migrations.AddField(
            model_name='intake',
            name='intake_housing_status',
            field=models.CharField(choices=[('homeless', 'Homeless'), ('at_risk', 'At Risk of Homelessness'), ('stably_housed', 'Stably Housed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='referral_source',
            field=models.CharField(choices=[('SMIS', 'SMIS'), ('EMHWare', 'EMHWare'), ('FFAI', 'FFAI')], db_index=True, default='SMIS', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suggested', 'Suggested')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='intake',
            index=models.Index(fields=['intake_date'], name='intake_date_idx'),
        ),
        migrations.AddIndex(
            model_name='intake',
            index=models.Index(fields=['referral_source'], name='intake_source_idx'),
        ),
        migrations.AddIndex(
            model_name='intake',
            index=models.Index(fields=['intake_housing_status'], name='intake_housing_idx'),
        ),
    ]
