# Generated by Django 4.2.7 on 2025-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_intake_source_system_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_phone_idx',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='immigration_status',
            new_name='citizenship_status',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='race',
            new_name='country_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_information',
            field=models.JSONField(default=dict, help_text='Contact information with phone and email'),
        ),
        migrations.AddField(
            model_name='client',
            name='ethnicity',
            field=models.JSONField(default=list, help_text='List of ethnicities (multi-select)'),
        ),
        migrations.AddField(
            model_name='client',
            name='indigenous_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['citizenship_status'], name='client_citizenship_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['indigenous_status'], name='client_indigenous_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['country_of_birth'], name='client_country_of_birth_idx'),
        ),
    ]
