# Generated by Django 4.2.7 on 2025-09-22 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migrate_contact_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField(db_index=True)),
                ('match_type', models.CharField(db_index=True, max_length=50)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('very_low', 'Very Low')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed_duplicate', 'Confirmed Duplicate'), ('not_duplicate', 'Not Duplicate'), ('merged', 'Merged')], db_index=True, default='pending', max_length=30)),
                ('match_details', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('duplicate_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of', to='core.client')),
                ('primary_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_duplicates', to='core.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
            ],
            options={
                'db_table': 'client_duplicates',
                'indexes': [models.Index(fields=['status', 'confidence_level'], name='client_dupl_status_bea7d3_idx'), models.Index(fields=['similarity_score'], name='client_dupl_similar_df3bb9_idx'), models.Index(fields=['match_type'], name='client_dupl_match_t_106a11_idx')],
                'unique_together': {('primary_client', 'duplicate_client')},
            },
        ),
    ]
