# Generated by Django 4.2.7 on 2025-09-30 11:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('core', '0009_client_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramServiceManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_managers', to='core.staff')),
                ('program_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='programs.programservice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_manager_assignments', to='core.staff')),
            ],
            options={
                'db_table': 'program_service_manager_assignments',
                'indexes': [models.Index(fields=['staff', 'is_active'], name='program_ser_staff_i_b99a7c_idx'), models.Index(fields=['program_service', 'is_active'], name='program_ser_program_c8e507_idx')],
                'unique_together': {('staff', 'program_service')},
            },
        ),
    ]
