# Generated by Django 4.2.7 on 2025-09-30 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_programservicemanagerassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_program_managers', to='core.staff')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='core.program')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_manager_assignments', to='core.staff')),
            ],
            options={
                'db_table': 'program_manager_assignments',
                'indexes': [models.Index(fields=['staff', 'is_active'], name='program_man_staff_i_b27d4f_idx'), models.Index(fields=['program', 'is_active'], name='program_man_program_5b85a4_idx')],
                'unique_together': {('staff', 'program')},
            },
        ),
    ]
