# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_programmanagerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_2',
            field=models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='permission_to_phone',
            field=models.BooleanField(db_index=True, default=False, help_text='Permission to contact by phone'),
        ),
        migrations.AddField(
            model_name='client',
            name='permission_to_email',
            field=models.BooleanField(db_index=True, default=False, help_text='Permission to contact by email'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_work',
            field=models.CharField(blank=True, help_text='Work phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_alt',
            field=models.CharField(blank=True, help_text='Alternative phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, help_text='External client ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Medical conditions', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_diagnosis',
            field=models.CharField(blank=True, help_text='Primary diagnosis', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='support_workers',
            field=models.JSONField(default=list, help_text='List of assigned support workers'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin',
            field=models.JSONField(default=dict, help_text='Next of kin contact information'),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact',
            field=models.JSONField(default=dict, help_text='Emergency contact information'),
        ),
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments and notes', null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id'], name='client_id_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['permission_to_phone'], name='client_permission_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['permission_to_email'], name='client_permission_email_idx'),
        ),
    ]
