# Generated by Django 4.2.7 on 2025-10-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_restriction_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerestriction',
            name='supporting_document',
            field=models.ImageField(blank=True, help_text='Supporting document or image for the restriction', null=True, upload_to='restrictions/'),
        ),
        migrations.AlterField(
            model_name='servicerestriction',
            name='restriction_type',
            field=models.CharField(choices=[('general', 'General Restriction'), ('bill_168', 'Bill 168 (Violence Against Staff)'), ('no_trespass', 'No Trespass Order'), ('behaviors', 'Behavioral Issues')], db_index=True, default='general', max_length=20),
        ),
    ]
