# Generated by Django 4.2.7 on 2025-10-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_comprehensive_client_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerestriction',
            name='reason',
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='behaviors',
            field=models.JSONField(default=list, help_text='List of behaviors that led to this restriction'),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='is_indefinite',
            field=models.BooleanField(db_index=True, default=False, help_text='Check if this restriction has no end date'),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the restriction', null=True),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='restriction_type',
            field=models.CharField(choices=[('general', 'General Restriction'), ('bill_168', 'Bill 168 (Violence Against Staff)'), ('no_trespass', 'No Trespass Order')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='servicerestriction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_date__isnull', True), ('is_indefinite', True)), ('is_indefinite', False), _connector='OR'), name='indefinite_restriction_no_end_date'),
        ),
    ]
