# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_supporting_document_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Name of the person who last updated this record', max_length=255, null=True),
        ),
    ]

