# Generated by Django 4.2.7 on 2025-10-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_behavioral_restrictions_and_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerestriction',
            name='supporting_document',
        ),
    ]
