# Generated by Django 4.2.7 on 2025-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_updated_by_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprogramenrollment',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Name of the person who last updated this record', max_length=255, null=True),
        ),
    ]
