# Generated by Django 4.2.7 on 2025-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_updated_by_to_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerestriction',
            name='created_by',
            field=models.CharField(blank=True, help_text='Name of the person who created this record', max_length=255, null=True),
        ),
    ]
