# Generated by Django 4.2.7 on 2025-10-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_image'),
        ('core', '0019_add_created_by_to_restriction'),
    ]

    operations = [
    ]
