# Generated by Django 4.2.7 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20251006_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, help_text='External client ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
