# Generated by Django 4.2.7 on 2025-10-08 08:45

from django.db import migrations


def populate_created_by(apps, schema_editor):
    """Populate created_by field for existing enrollments"""
    ClientProgramEnrollment = apps.get_model('core', 'ClientProgramEnrollment')
    
    # Update enrollments that have updated_by but no created_by
    enrollments = ClientProgramEnrollment.objects.filter(
        created_by__isnull=True,
        updated_by__isnull=False
    )
    
    for enrollment in enrollments:
        # Use the updated_by value as created_by
        enrollment.created_by = enrollment.updated_by
        enrollment.save()
    
    # For enrollments that have neither created_by nor updated_by, set to 'System'
    enrollments_without_creator = ClientProgramEnrollment.objects.filter(
        created_by__isnull=True,
        updated_by__isnull=True
    )
    
    for enrollment in enrollments_without_creator:
        enrollment.created_by = 'System'
        enrollment.save()


def reverse_populate_created_by(apps, schema_editor):
    """Reverse the population by setting created_by back to None"""
    ClientProgramEnrollment = apps.get_model('core', 'ClientProgramEnrollment')
    
    # Set created_by back to None for all enrollments
    ClientProgramEnrollment.objects.all().update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_archived_to_enrollment'),
    ]

    operations = [
        migrations.RunPython(populate_created_by, reverse_populate_created_by),
    ]
