# Generated by Django 4.2.7 on 2025-10-09 06:56

from django.db import migrations, models


def update_existing_programs_capacity(apps, schema_editor):
    """Update existing programs with capacity_current = 0 to have capacity_current = 100"""
    Program = apps.get_model('core', 'Program')
    Program.objects.filter(capacity_current=0).update(capacity_current=100)


def reverse_update_existing_programs_capacity(apps, schema_editor):
    """Reverse migration - set programs with capacity_current = 100 back to 0"""
    Program = apps.get_model('core', 'Program')
    Program.objects.filter(capacity_current=100).update(capacity_current=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_populate_created_by_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='capacity_current',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.RunPython(
            update_existing_programs_capacity,
            reverse_update_existing_programs_capacity,
        ),
        migrations.DeleteModel(
            name='PendingChange',
        ),
    ]
