# Generated by Django 4.2.7 on 2025-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_set_default_program_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerestriction',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Check if this restriction has been archived'),
        ),
    ]
