# Generated by Django 4.2.7 on 2025-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_archived_to_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='aboriginal_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='admission_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, help_text='Calculated from DOB', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='chart_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='children_home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='children_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='days_elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='discharge_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='family_doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender_identity',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='health_card_exp_date',
            field=models.DateField(blank=True, help_text='HC Exp Date', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='health_card_issuing_province',
            field=models.CharField(blank=True, help_text='HC Issuing Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='health_card_number',
            field=models.CharField(blank=True, db_index=True, help_text='HC# (Health Card Number)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='health_card_version',
            field=models.CharField(blank=True, help_text='HC Version', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='highest_level_education',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='language_interpreter_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='level_of_support',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lgbtq_status',
            field=models.CharField(blank=True, db_index=True, help_text='LGBTQ+ Status', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lhin',
            field=models.CharField(blank=True, db_index=True, help_text='Local Health Integration Network', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location_county',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mother_tongue',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='no_health_card_reason',
            field=models.CharField(blank=True, help_text='No HC Reason', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='official_language',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_language',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='program',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='program_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pronoun',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='reason_discharge',
            field=models.CharField(blank=True, help_text='Reason for Discharge/Program Status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='receiving_services',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='self_identification_race_ethnicity',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sub_program',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='alias',
            field=models.CharField(blank=True, db_index=True, help_text='Last Name at Birth', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['chart_number'], name='client_chart_number_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['program'], name='client_program_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['program_status'], name='client_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='client_type_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['admission_date'], name='client_admission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['discharge_date'], name='client_discharge_date_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['health_card_number'], name='client_health_card_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['lhin'], name='client_lhin_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['location_county'], name='client_location_county_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['province'], name='client_province_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city'], name='client_city_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['postal_code'], name='client_postal_code_idx'),
        ),
    ]
