# Generated by Django 4.2.7 on 2025-10-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_comprehensive_client_fields_v2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_program_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_program_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_admission_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_discharge_date_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='days_elapsed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='level_of_support',
        ),
        migrations.RemoveField(
            model_name='client',
            name='program',
        ),
        migrations.RemoveField(
            model_name='client',
            name='program_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reason_discharge',
        ),
        migrations.RemoveField(
            model_name='client',
            name='receiving_services',
        ),
        migrations.RemoveField(
            model_name='client',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sub_program',
        ),
        migrations.RemoveField(
            model_name='client',
            name='support_workers',
        ),
    ]
