# Generated by Django 4.2.7 on 2025-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_program_fields_from_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admission_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='days_elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='discharge_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='level_of_support',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='program',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='program_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='reason_discharge',
            field=models.CharField(blank=True, help_text='Reason for Discharge/Program Status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='receiving_services',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sub_program',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='support_workers',
            field=models.JSONField(default=list, help_text='List of assigned support workers'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['program'], name='client_program_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['program_status'], name='client_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='client_type_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['admission_date'], name='client_admission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['discharge_date'], name='client_discharge_date_idx'),
        ),
    ]
