# Generated by Django 4.2.7 on 2025-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_subprogram_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprogramenrollment',
            name='days_elapsed',
            field=models.IntegerField(blank=True, help_text='Number of days elapsed since enrollment start', null=True),
        ),
        migrations.AddField(
            model_name='clientprogramenrollment',
            name='receiving_services_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when client started receiving services', null=True),
        ),
    ]
