# Generated by Django 4.2.7 on 2025-10-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_enrollment_details_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='receiving_services_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when client started receiving services', null=True),
        ),
    ]
