# Generated by Django 4.2.7 on 2025-10-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_receiving_services_date_to_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='receiving_services_date',
        ),
    ]
