# Generated by Django 4.2.7 on 2025-10-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_client_receiving_services_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerestriction',
            name='is_bill_168',
            field=models.BooleanField(db_index=True, default=False, help_text='Check if this is a Bill 168 (Violence Against Staff) restriction'),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='is_no_trespass',
            field=models.BooleanField(db_index=True, default=False, help_text='Check if this is a No Trespass Order'),
        ),
        migrations.AlterField(
            model_name='servicerestriction',
            name='restriction_type',
            field=models.CharField(choices=[('general', 'General Restriction'), ('behaviors', 'Behavioral Issues')], db_index=True, default='general', max_length=20),
        ),
    ]
