# Generated by Django 4.2.7 on 2025-10-10 12:43

from django.db import migrations
import json


def convert_restriction_type_to_json(apps, schema_editor):
    ServiceRestriction = apps.get_model('core', 'ServiceRestriction')
    
    for restriction in ServiceRestriction.objects.all():
        # Convert old string values to JSON arrays
        old_value = restriction.restriction_type
        
        if old_value == 'general':
            restriction.restriction_type = []
        elif old_value == 'behaviors':
            restriction.restriction_type = []
        elif old_value == 'bill_168':
            restriction.restriction_type = []
        elif old_value == 'no_trespass':
            restriction.restriction_type = []
        else:
            restriction.restriction_type = []
        
        restriction.save()


def reverse_convert_restriction_type_to_json(apps, schema_editor):
    ServiceRestriction = apps.get_model('core', 'ServiceRestriction')
    
    for restriction in ServiceRestriction.objects.all():
        # Convert JSON arrays back to string values
        if isinstance(restriction.restriction_type, list):
            if not restriction.restriction_type:
                restriction.restriction_type = 'general'
            else:
                restriction.restriction_type = restriction.restriction_type[0] if restriction.restriction_type else 'general'
        else:
            restriction.restriction_type = 'general'
        
        restriction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_bill_168_no_trespass_fields'),
    ]

    operations = [
        migrations.RunPython(convert_restriction_type_to_json, reverse_convert_restriction_type_to_json),
    ]
