# Generated by Django 4.2.7 on 2025-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_convert_restriction_type_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerestriction',
            name='restriction_type',
            field=models.JSONField(default=list, help_text='List of behaviors that led to this restriction'),
        ),
    ]
