# Generated by Django 4.2.7 on 2025-10-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_change_restriction_type_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerestriction',
            name='restriction_type',
            field=models.CharField(choices=[('aggressive', 'Aggressive'), ('harassment', 'Harassment'), ('theft', 'Theft'), ('threatening', 'Threatening'), ('intoxicated', 'Intoxicated'), ('property_damage', 'Property Damage')], help_text='Behavior that led to this restriction', max_length=50),
        ),
    ]
