# Generated by Django 4.2.7 on 2025-10-10 12:58

from django.db import migrations
import json


def convert_restriction_type_to_json(apps, schema_editor):
    ServiceRestriction = apps.get_model('core', 'ServiceRestriction')
    
    for restriction in ServiceRestriction.objects.all():
        if restriction.restriction_type:
            # Convert single string value to list
            if isinstance(restriction.restriction_type, str):
                restriction.restriction_type = [restriction.restriction_type]
            # If it's already a list, keep it as is
            elif isinstance(restriction.restriction_type, list):
                pass
            else:
                restriction.restriction_type = []
        else:
            restriction.restriction_type = []
        restriction.save()


def reverse_convert_restriction_type_to_json(apps, schema_editor):
    ServiceRestriction = apps.get_model('core', 'ServiceRestriction')
    
    for restriction in ServiceRestriction.objects.all():
        if restriction.restriction_type:
            # Convert list back to single string (take first item)
            if isinstance(restriction.restriction_type, list) and len(restriction.restriction_type) > 0:
                restriction.restriction_type = restriction.restriction_type[0]
            else:
                restriction.restriction_type = ''
        else:
            restriction.restriction_type = ''
        restriction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_change_restriction_type_to_jsonfield'),
    ]

    operations = [
        migrations.RunPython(convert_restriction_type_to_json, reverse_convert_restriction_type_to_json),
    ]
