# Generated by Django 4.2.7 on 2025-10-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_convert_restriction_type_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('import', 'Import'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=20),
        ),
    ]
