# Generated by Django 4.2.7 on 2025-10-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_login_logout_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-hierarchy_level', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='can_assign_roles',
            field=models.BooleanField(default=False, help_text='Can this role assign roles to other users?'),
        ),
        migrations.AddField(
            model_name='role',
            name='hierarchy_level',
            field=models.IntegerField(default=0, help_text='Higher numbers have more privileges'),
        ),
    ]
