# Generated by Django 4.2.7 on 2025-10-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_role_hierarchy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_assign_roles',
        ),
        migrations.RemoveField(
            model_name='role',
            name='hierarchy_level',
        ),
    ]
