# Generated by Django 4.2.7 on 2025-10-14 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_role_options_remove_role_can_assign_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLeaderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_department_leaders', to='core.staff')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_assignments', to='core.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_leader_assignments', to='core.staff')),
            ],
            options={
                'db_table': 'department_leader_assignments',
                'indexes': [models.Index(fields=['staff', 'is_active'], name='department__staff_i_8893cd_idx'), models.Index(fields=['department', 'is_active'], name='department__departm_f1c433_idx')],
                'unique_together': {('staff', 'department')},
            },
        ),
    ]
