# Generated by Django 4.2.7 on 2025-10-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_department_leader_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('SMIS', 'SMIS'), ('EMHware', 'EMHware')], db_index=True, help_text='Source system where client data originated', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['source'], name='client_source_idx'),
        ),
    ]
