# Generated by Django 4.2.7 on 2025-10-16 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_client_source_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(help_text='Name of the recipient', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this recipient', null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: restrict to specific department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
            options={
                'db_table': 'email_recipients',
                'indexes': [models.Index(fields=['email', 'is_active'], name='email_recip_email_107fe4_idx'), models.Index(fields=['department', 'is_active'], name='email_recip_departm_d63ea9_idx')],
            },
        ),
    ]
