# Generated by Django 4.2.7 on 2025-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_emailrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily (Last 24 Hours)'), ('weekly', 'Weekly (Last 7 Days)'), ('monthly', 'Monthly (Last 30 Days)')], default='daily', help_text='How often to send reports', max_length=20),
        ),
    ]
