# Generated by Django 4.2.7 on 2025-10-16 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_frequency_to_email_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('daily_report', 'Daily Client Report'), ('weekly_report', 'Weekly Client Report'), ('monthly_report', 'Monthly Client Report'), ('test_email', 'Test Email'), ('custom', 'Custom Email')], default='daily_report', max_length=20)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Name of the recipient', max_length=255, null=True)),
                ('email_body', models.TextField(help_text='HTML content of the email')),
                ('csv_attachment', models.TextField(blank=True, help_text='CSV data that was attached', null=True)),
                ('csv_filename', models.CharField(blank=True, help_text='Name of the CSV file attached', max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the email was sent')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('client_count', models.PositiveIntegerField(default=0, help_text='Number of clients included in the report')),
                ('report_date', models.DateField(help_text='Date the report covers')),
                ('frequency', models.CharField(choices=[('daily', 'Daily (Last 24 Hours)'), ('weekly', 'Weekly (Last 7 Days)'), ('monthly', 'Monthly (Last 30 Days)')], default='daily', max_length=20)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient_email', 'sent_at'], name='email_logs_recipie_d34e09_idx'), models.Index(fields=['email_type', 'status'], name='email_logs_email_t_022709_idx'), models.Index(fields=['report_date'], name='email_logs_report__b38c89_idx'), models.Index(fields=['sent_at'], name='email_logs_sent_at_9fc48d_idx')],
            },
        ),
    ]
