# Generated by Django 4.2.7 on 2025-10-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_emaillog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={'permissions': [('manage_email_subscriptions', 'Can manage email subscriptions')]},
        ),
    ]
