# Generated by Django 4.2.7 on 2025-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_emailrecipient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='receiving_services_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when client actually started receiving services', null=True),
        ),
    ]
