# Generated by Django 4.2.7 on 2025-10-17 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_receiving_services_date_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indigenous_identity', models.CharField(blank=True, max_length=200, null=True)),
                ('military_status', models.CharField(blank=True, max_length=200, null=True)),
                ('refugee_status', models.CharField(blank=True, max_length=200, null=True)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('family_head_client_no', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_worker', models.CharField(blank=True, max_length=200, null=True)),
                ('chronically_homeless', models.BooleanField(default=False)),
                ('num_bednights_current_stay', models.IntegerField(blank=True, null=True)),
                ('length_homeless_3yrs', models.IntegerField(blank=True, null=True)),
                ('income_source', models.CharField(blank=True, max_length=200, null=True)),
                ('taxation_year_filed', models.CharField(blank=True, max_length=4, null=True)),
                ('status_id', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_id', models.CharField(blank=True, max_length=200, null=True)),
                ('other_id', models.CharField(blank=True, max_length=200, null=True)),
                ('bnl_consent', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('harm_reduction_support', models.BooleanField(default=False)),
                ('medication_support', models.BooleanField(default=False)),
                ('pregnancy_support', models.BooleanField(default=False)),
                ('mental_health_support', models.BooleanField(default=False)),
                ('physical_health_support', models.BooleanField(default=False)),
                ('daily_activities_support', models.BooleanField(default=False)),
                ('other_health_supports', models.TextField(blank=True, null=True)),
                ('cannot_use_stairs', models.BooleanField(default=False)),
                ('limited_mobility', models.BooleanField(default=False)),
                ('wheelchair_accessibility', models.BooleanField(default=False)),
                ('vision_hearing_speech_supports', models.TextField(blank=True, null=True)),
                ('english_translator', models.BooleanField(default=False)),
                ('reading_supports', models.BooleanField(default=False)),
                ('other_accessibility_supports', models.TextField(blank=True, null=True)),
                ('pet_owner', models.BooleanField(default=False)),
                ('legal_support', models.BooleanField(default=False)),
                ('immigration_support', models.BooleanField(default=False)),
                ('religious_cultural_supports', models.TextField(blank=True, null=True)),
                ('safety_concerns', models.TextField(blank=True, null=True)),
                ('intimate_partner_violence_support', models.BooleanField(default=False)),
                ('human_trafficking_support', models.BooleanField(default=False)),
                ('other_supports', models.TextField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='core.client')),
            ],
            options={
                'db_table': 'client_extended',
            },
        ),
    ]
