# Generated by Django 4.2.7 on 2025-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_clientextended'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientextended',
            name='access_point_application',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='access_point_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='access_to_housing_application',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='access_to_housing_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='bed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='bed_nights_historical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='cars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='cars_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='discharge_disposition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='early_termination_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='intake_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='intake_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='lived_last_12_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='occupancy_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='reason_for_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='rejection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='restriction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='restriction_duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='restriction_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='restriction_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientextended',
            name='service_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
