# Generated by Django 4.2.7 on 2025-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_clientextended_access_point_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientextended',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
