# Generated by Django 4.2.7 on 2025-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_clientextended_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
