# Generated by Django 4.2.7 on 2025-10-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_make_dob_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            # Set default value for existing null ethnicity records
            "UPDATE clients SET ethnicity = '[]'::jsonb WHERE ethnicity IS NULL;",
            # Reverse operation
            "UPDATE clients SET ethnicity = NULL WHERE ethnicity = '[]'::jsonb;"
        ),
        migrations.RunSQL(
            # Make ethnicity column nullable
            "ALTER TABLE clients ALTER COLUMN ethnicity DROP NOT NULL;",
            # Reverse operation
            "ALTER TABLE clients ALTER COLUMN ethnicity SET NOT NULL;"
        ),
        migrations.RunSQL(
            # Set default value for the column
            "ALTER TABLE clients ALTER COLUMN ethnicity SET DEFAULT '[]'::jsonb;",
            # Reverse operation
            "ALTER TABLE clients ALTER COLUMN ethnicity DROP DEFAULT;"
        ),
    ]
