# Generated by Django 4.2.7 on 2025-10-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_fix_ethnicity_nullable'),
    ]

    operations = [
        # Fix JSON fields to be nullable and have proper defaults
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN addresses DROP NOT NULL;",
            "ALTER TABLE clients ALTER COLUMN addresses SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN addresses SET DEFAULT '[]'::jsonb;",
            "ALTER TABLE clients ALTER COLUMN addresses DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN contact_information DROP NOT NULL;",
            "ALTER TABLE clients ALTER COLUMN contact_information SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN contact_information SET DEFAULT '{}'::jsonb;",
            "ALTER TABLE clients ALTER COLUMN contact_information DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN emergency_contact DROP NOT NULL;",
            "ALTER TABLE clients ALTER COLUMN emergency_contact SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN emergency_contact SET DEFAULT '{}'::jsonb;",
            "ALTER TABLE clients ALTER COLUMN emergency_contact DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN languages_spoken DROP NOT NULL;",
            "ALTER TABLE clients ALTER COLUMN languages_spoken SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN languages_spoken SET DEFAULT '[]'::jsonb;",
            "ALTER TABLE clients ALTER COLUMN languages_spoken DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN next_of_kin DROP NOT NULL;",
            "ALTER TABLE clients ALTER COLUMN next_of_kin SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN next_of_kin SET DEFAULT '{}'::jsonb;",
            "ALTER TABLE clients ALTER COLUMN next_of_kin DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN support_workers DROP NOT NULL;",
            "ALTER TABLE clients ALTER COLUMN support_workers SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN support_workers SET DEFAULT '[]'::jsonb;",
            "ALTER TABLE clients ALTER COLUMN support_workers DROP DEFAULT;"
        ),
        
        # Fix boolean fields to have proper defaults
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN children_home SET DEFAULT false;",
            "ALTER TABLE clients ALTER COLUMN children_home DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN language_interpreter_required SET DEFAULT false;",
            "ALTER TABLE clients ALTER COLUMN language_interpreter_required DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN permission_to_email SET DEFAULT false;",
            "ALTER TABLE clients ALTER COLUMN permission_to_email DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN permission_to_phone SET DEFAULT false;",
            "ALTER TABLE clients ALTER COLUMN permission_to_phone DROP DEFAULT;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE clients ALTER COLUMN receiving_services SET DEFAULT false;",
            "ALTER TABLE clients ALTER COLUMN receiving_services DROP DEFAULT;"
        ),
    ]
