# Generated by Django 4.2.7 on 2025-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_fix_all_nullable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.CharField(blank=True, help_text='Name of the person who created this record', max_length=255, null=True),
        ),
    ]
