# Generated by Django 4.2.7 on 2025-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_created_by_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='referral_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
