# Generated by Django 4.2.7 on 2025-10-29 07:23

from django.db import migrations


def populate_created_by_for_existing_clients(apps, schema_editor):
    """Populate created_by field for existing clients that don't have it set"""
    Client = apps.get_model('core', 'Client')
    
    # Update clients that have updated_by but no created_by
    clients_with_updated_by = Client.objects.filter(
        created_by__isnull=True,
        updated_by__isnull=False
    )
    
    for client in clients_with_updated_by:
        # Use the updated_by value as created_by
        client.created_by = client.updated_by
        client.save(update_fields=['created_by'])
    
    # For clients that have neither created_by nor updated_by, set to 'System'
    clients_without_creator = Client.objects.filter(
        created_by__isnull=True,
        updated_by__isnull=True
    )
    
    for client in clients_without_creator:
        client.created_by = 'System'
        client.save(update_fields=['created_by'])


def reverse_populate_created_by_for_existing_clients(apps, schema_editor):
    """Reverse the population by setting created_by back to None"""
    Client = apps.get_model('core', 'Client')
    
    # Set created_by back to None for clients that were set to 'System'
    Client.objects.filter(created_by='System').update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_fix_referral_source_length'),
    ]

    operations = [
        migrations.RunPython(
            populate_created_by_for_existing_clients,
            reverse_populate_created_by_for_existing_clients
        ),
    ]
