# Generated by Django 4.2.7 on 2025-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_populate_created_by_for_existing_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.CharField(blank=True, help_text='Name of the person who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Name of the person who last updated this record', max_length=255, null=True),
        ),
    ]
