# Generated by Django 4.2.7 on 2025-10-29 07:31

from django.db import migrations


def populate_audit_fields_for_programs(apps, schema_editor):
    """Populate created_by and updated_by fields for existing programs"""
    Program = apps.get_model('core', 'Program')
    
    # Set all existing programs to have 'System' as created_by and updated_by
    Program.objects.all().update(
        created_by='System',
        updated_by='System'
    )


def reverse_populate_audit_fields_for_programs(apps, schema_editor):
    """Reverse the population by setting created_by and updated_by back to None"""
    Program = apps.get_model('core', 'Program')
    
    # Set created_by and updated_by back to None
    Program.objects.all().update(
        created_by=None,
        updated_by=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_audit_fields_to_program'),
    ]

    operations = [
        migrations.RunPython(
            populate_audit_fields_for_programs,
            reverse_populate_audit_fields_for_programs
        ),
    ]
