# Generated by Django 4.2.7 on 2025-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_update_department_owner_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
