# Generated by Django 4.2.7 on 2025-11-03 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_client_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprogramenrollment',
            options={'ordering': ['-start_date', 'program__name']},
        ),
        migrations.CreateModel(
            name='ClientUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(db_index=True, help_text='csv, xlsx, or xls', max_length=10)),
                ('source', models.CharField(db_index=True, help_text='SMIS or EMHware', max_length=50)),
                ('total_rows', models.IntegerField(default=0, help_text='Total number of rows in the uploaded file')),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('duplicates_flagged', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True, help_text='When the upload process started')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text='When the upload process completed', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Upload duration in seconds', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if upload failed', null=True)),
                ('error_details', models.JSONField(default=list, help_text='List of error messages from processing')),
                ('upload_details', models.JSONField(default=dict, help_text='Additional upload metadata')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_uploads', to='core.staff')),
            ],
            options={
                'db_table': 'client_upload_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='client_uplo_status_0be871_idx'), models.Index(fields=['uploaded_by', 'started_at'], name='client_uplo_uploade_bc2552_idx'), models.Index(fields=['source', 'started_at'], name='client_uplo_source_91e188_idx')],
            },
        ),
    ]
