# Generated by Django 4.2.7 on 2025-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_add_client_upload_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this client was archived', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this client is archived'),
        ),
        migrations.AddField(
            model_name='clientprogramenrollment',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this enrollment was archived', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this department was archived', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this department is archived'),
        ),
        migrations.AddField(
            model_name='program',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this program was archived', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this program is archived'),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this restriction was archived', null=True),
        ),
    ]
