# Generated by Django 4.2.7 on 2025-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_client_archived_at_client_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('import', 'Import'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=20),
        ),
    ]
