# Generated by Django 4.2.7 on 2025-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_add_restore_action_to_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_inactive',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this client is inactive (has zero active enrollments)'),
        ),
    ]
