# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_client_is_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerestriction',
            name='entered_by',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text='Staff member who entered this restriction',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='restrictions_entered',
                to='core.staff'
            ),
        ),
    ]

