# Generated by Django 4.2.7 on 2025-11-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_entered_by_to_service_restriction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerestriction',
            name='valid_scope_program_combination',
        ),
        migrations.AlterField(
            model_name='servicerestriction',
            name='scope',
            field=models.CharField(choices=[('org', 'Agency-wide'), ('program', 'Program-Specific')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='servicerestriction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('program__isnull', False), ('scope', 'program')), ('scope', 'org'), _connector='OR'), name='valid_scope_program_combination'),
        ),
    ]
