# Generated by Django 4.2.7 on 2025-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_program_no_capacity_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientextended',
            name='taxation_year_filed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
