# Generated by Django 4.2.7 on 2025-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_rename_notifications_staff_i_c13930_idx_notificatio_staff_i_fd6636_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='veteran_status',
            field=models.CharField(blank=True, db_index=True, help_text='Veteran Status', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_status',
            field=models.CharField(blank=True, db_index=True, help_text='Legal Status', max_length=100, null=True),
        ),
    ]

