# Generated by Django 4.2.7 on 2025-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_add_veteran_legal_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_communication_method',
            field=models.CharField(blank=True, db_index=True, help_text='Preferred Method of Communication', max_length=50, null=True),
        ),
    ]

