# Generated by Django 4.2.7 on 2025-11-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rename_notifications_staff_i_c13930_idx_notificatio_staff_i_fd6636_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_communication_method',
            field=models.CharField(blank=True, db_index=True, help_text='Preferred Method of Communication', max_length=50, null=True),
        ),
    ]
