# Generated by Django 4.2.7 on 2025-11-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_detection_source_to_client_duplicate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_staff_i_fd6636_idx',
            old_name='notifications_staff_i_c13930_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_categor_57c79b_idx',
            old_name='notifications_category_42eb20_idx',
        ),
    ]
