# Generated by Django 4.2.7 on 2025-11-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerestriction',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this restriction was approved', null=True),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved this restriction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions_approved', to='core.staff'),
        ),
        migrations.AddField(
            model_name='servicerestriction',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this restriction has been approved by SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('service_restriction', 'Service Restriction'), ('restriction_approval', 'Restriction Approval')], default='service_restriction', max_length=100),
        ),
    ]
