# Generated by Django 4.2.7 on 2025-12-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_add_restriction_approval_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_citizenship_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_indigenous_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_country_of_birth_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_permission_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_permission_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_chart_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_health_card_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_lhin_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_location_county_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_province_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_program_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_program_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_admission_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_source_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='aboriginal_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='alias',
            field=models.CharField(blank=True, help_text='Last Name at Birth', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='chart_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='children_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='citizenship_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='emhware_id',
            field=models.CharField(blank=True, help_text='Client ID from EMHware system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender_identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_card_number',
            field=models.CharField(blank=True, help_text='HC# (Health Card Number)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='highest_level_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='indigenous_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='language_interpreter_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_status',
            field=models.CharField(blank=True, help_text='Legal Status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='level_of_support',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lgbtq_status',
            field=models.CharField(blank=True, help_text='LGBTQ+ Status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lhin',
            field=models.CharField(blank=True, help_text='Local Health Integration Network', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='location_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='official_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='permission_to_email',
            field=models.BooleanField(default=False, help_text='Permission to contact by email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='permission_to_phone',
            field=models.BooleanField(default=False, help_text='Permission to contact by phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_communication_method',
            field=models.CharField(blank=True, help_text='Preferred Method of Communication', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='program_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pronoun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='receiving_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='receiving_services_date',
            field=models.DateField(blank=True, help_text='Date when client actually started receiving services', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='secondary_source_id',
            field=models.CharField(blank=True, help_text='Client ID of the duplicate client that was merged into this client', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='self_identification_race_ethnicity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexual_orientation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='smis_id',
            field=models.CharField(blank=True, help_text='Client ID from SMIS system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sub_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='veteran_status',
            field=models.CharField(blank=True, help_text='Veteran Status', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id', 'source'], name='client_id_source_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['dob'], name='client_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_archived', 'is_inactive'], name='client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['source', 'is_archived'], name='client_source_archived_idx'),
        ),
    ]
