# Generated by Django 4.2.7 on 2025-09-12 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_client_address_client_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
            options={
                'db_table': 'staff_schedules',
                'indexes': [models.Index(fields=['staff', 'day_of_week'], name='staff_sched_staff_i_7a109d_idx'), models.Index(fields=['is_active'], name='staff_sched_is_acti_1ebf48_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_name', models.CharField(db_index=True, max_length=255)),
                ('is_granted', models.BooleanField(db_index=True, default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to='core.staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
            options={
                'db_table': 'staff_permissions',
                'indexes': [models.Index(fields=['staff', 'permission_name'], name='staff_permi_staff_i_49a45d_idx'), models.Index(fields=['is_granted'], name='staff_permi_is_gran_e82c62_idx'), models.Index(fields=['expires_at'], name='staff_permi_expires_268e3e_idx')],
                'unique_together': {('staff', 'permission_name')},
            },
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(db_index=True, default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
            options={
                'db_table': 'staff_notes',
                'indexes': [models.Index(fields=['staff', 'created_at'], name='staff_notes_staff_i_666069_idx'), models.Index(fields=['is_private'], name='staff_notes_is_priv_56bc1c_idx')],
            },
        ),
    ]
