# Generated by Django 4.2.7 on 2025-10-13 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_role_options_remove_role_can_assign_roles_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('client', 'Client'), ('program', 'Program')], db_index=True, max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='core.staff')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.client')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.program')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.staff')),
            ],
            options={
                'db_table': 'staff_assignments',
                'indexes': [models.Index(fields=['staff', 'assignment_type'], name='staff_assig_staff_i_b6982b_idx'), models.Index(fields=['staff', 'is_active'], name='staff_assig_staff_i_6e9fc1_idx'), models.Index(fields=['client', 'is_active'], name='staff_assig_client__8295a7_idx'), models.Index(fields=['program', 'is_active'], name='staff_assig_program_7beb02_idx'), models.Index(fields=['assigned_by'], name='staff_assig_assigne_fb154c_idx'), models.Index(fields=['assigned_at'], name='staff_assig_assigne_8939de_idx')],
                'unique_together': {('staff', 'client'), ('staff', 'program')},
            },
        ),
    ]
