# Generated by Django 4.2.7 on 2025-10-13 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_role_options_remove_role_can_assign_roles_and_more'),
        ('staff', '0002_staffassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_staff', to='core.staff')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='core.staff')),
            ],
            options={
                'db_table': 'staff_client_assignments',
            },
        ),
        migrations.CreateModel(
            name='StaffProgramAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_program_staff', to='core.staff')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.program')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='core.staff')),
            ],
            options={
                'db_table': 'staff_program_assignments',
            },
        ),
        migrations.DeleteModel(
            name='StaffAssignment',
        ),
        migrations.AddIndex(
            model_name='staffprogramassignment',
            index=models.Index(fields=['staff', 'is_active'], name='staff_progr_staff_i_5820a2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprogramassignment',
            index=models.Index(fields=['program', 'is_active'], name='staff_progr_program_c5c335_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffprogramassignment',
            unique_together={('staff', 'program')},
        ),
        migrations.AddIndex(
            model_name='staffclientassignment',
            index=models.Index(fields=['staff', 'is_active'], name='staff_clien_staff_i_c50622_idx'),
        ),
        migrations.AddIndex(
            model_name='staffclientassignment',
            index=models.Index(fields=['client', 'is_active'], name='staff_clien_client__df0dc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffclientassignment',
            unique_together={('staff', 'client')},
        ),
    ]
