# Generated by Django 4.2.7 on 2025-10-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffdepartmentassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffDepartmentAssignment',
        ),
    ]
