# Generated by Django 4.2.7 on 2025-10-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        # Remove unique constraints on email and phone to allow duplicates
        migrations.RunSQL(
            "ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_email_key;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_phone_key;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        # Also remove any unique constraints on contact_information fields
        migrations.RunSQL(
            "ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_contact_information_key;",
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
