# Generated by Django 4.2.7 on 2025-09-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['client', 'created_at'], name='client_note_client__80ca07_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['is_private'], name='client_note_is_priv_e483ca_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'created_at'], name='client_docu_client__c18120_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['file_type'], name='client_docu_file_ty_a17f76_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'contact_type'], name='client_cont_client__7de7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['is_primary'], name='client_cont_is_prim_5ef9d5_idx'),
        ),
    ]
