# Generated by Django 4.2.7 on 2025-10-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20251006_1148'),
    ]

    operations = [
        # Remove unique constraint from client_id to allow auto-generation
        migrations.RunSQL(
            "ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_client_id_key;",
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
