# Generated by Django 4.2.7 on 2025-10-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20251006_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocument',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientnote',
            name='client',
        ),
        migrations.DeleteModel(
            name='ClientContact',
        ),
        migrations.DeleteModel(
            name='ClientDocument',
        ),
        migrations.DeleteModel(
            name='ClientNote',
        ),
    ]
