# Generated by Django 4.2.7 on 2025-09-12 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_client_address_client_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'db_table': 'program_services',
                'indexes': [models.Index(fields=['program', 'is_active'], name='program_ser_program_53c237_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField(default=dict)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'db_table': 'program_locations',
                'indexes': [models.Index(fields=['program', 'is_primary'], name='program_loc_program_2a397f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('capacity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'db_table': 'program_capacities',
                'indexes': [models.Index(fields=['program', 'effective_date'], name='program_cap_program_bdcc42_idx')],
                'unique_together': {('program', 'effective_date')},
            },
        ),
    ]
